image: golang:alpine
pipelines:
  branches:
    main:
      - parallel:
          - step:
              name: FMP_APIs - Develop - build and deploy
              script:
                - apk add --no-cache git zip openssh-client
                - rm -rf ./config
                - git clone git@bitbucket.org:wisdomfish/fmp_config.git ./config
                - ls ./config
                - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags debug -ldflags="-w -s" -o deploy/fms cmd/fms/fms.go
                - zip -D -j -r deploy/fms.zip deploy/fms
                - rm -rf  /opt/atlassian/pipelines/agent/build/.bitbucket/pipelines/generated/pipeline/pipes
                - pipe: atlassian/aws-lambda-deploy:1.10.0
                  variables:
                    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                    FUNCTION_NAME: fmp-testing
                    COMMAND: update
                    ZIP_FILE: deploy/fms.zip
