### login
POST {{host}}/fms/web/v1.0/login
Content-Type: application/json

{
  "fleet_code": "A12345",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
GET {{host}}/fms/web/v1.0/clients?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/fms/web/v1.0/clients/1630fe6c-47e5-4fc6-88d6-3507fe2c01e9
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/fms/web/v1.0/clients
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "test"
}

### Update
PATCH {{host}}/fms/web/v1.0/clients/006d4bdd-e9aa-4861-8ca3-58e7311ef3fd
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "車A"
}

### Delete
DELETE {{host}}/fms/web/v1.0/clients/d1db267b-f8d9-4056-b3b9-9c7f7e7f59be
Accept: application/json
Authorization: Bearer {{accessToken}}