### login
POST {{host}}/fms/web/v1.0/login
Content-Type: application/json

{
  "fleet_code": "A12345",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetAllPolicies
GET {{host}}/fms/web/v1.0/policies
Accept: application/json
Authorization: Bearer {{accessToken}}

### AddPolicy
POST {{host}}/fms/web/v1.0/policies
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ptype": "p",
  "role_name": "admin",
  "path": "/fms/*",
  "method": "GET"
}

### DeletePolicy
DELETE {{host}}/fms/web/v1.0/policies
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ptype": "p",
  "role_name": "admin",
  "path": "/fms/*",
  "method": "GET"
}
